### ISSUE TITLE
翻译进度

### ISSUE THREAD

**Issue by ColourfulBlack** [Modern-CMake-CN/Modern-CMake-zh_CN#16]
* [x] [An Introduction to Modern CMake](../blob/master/README_GitBook.md)
    * [x] [Installing CMake](../blob/master/chapters/intro/installing.md)
    * [x] [Running CMake](../blob/master/chapters/intro/running.md)
    * [x] [Do's and Don'ts](../blob/master/chapters/intro/dodonot.md)
    * [x] [What's new in CMake](../blob/master/chapters/intro/newcmake.md)
* [x] [Introduction to the Basics](../blob/master/chapters/basics.md)
    * [x] [Variables and the Cache](../blob/master/chapters/basics/variables.md)
    * [x] [Programming in CMake](../blob/master/chapters/basics/functions.md)
    * [x] [Communicating with your code](../blob/master/chapters/basics/comms.md)
    * [x] [How to Structure Your Project](../blob/master/chapters/basics/structure.md)
    * [x] [Running Other Programs](../blob/master/chapters/basics/programs.md)
    * [x] [A Simple Example](../blob/master/chapters/basics/example.md)
* [x] [Adding Features](../blob/master/chapters/features.md)
    * [x] [C++11 and Beyond](../blob/master/chapters/features/cpp11.md)
    * [x] [Small but common needs](../blob/master/chapters/features/small.md)
    * [x] [Utilities](../blob/master/chapters/features/utilities.md)
    * [x] [Useful modules](../blob/master/chapters/features/modules.md)
    * [x] [IDEs](../blob/master/chapters/features/ides.md)
    * [x] [Debugging](../blob/master/chapters/features/debug.md)
* [x] [Including Projects](../blob/master/chapters/projects.md)
    * [x] [Submodule](../blob/master/chapters/projects/submodule.md)
    * [x] [DownloadProject](../blob/master/chapters/projects/download.md)
    * [x] [Fetch (CMake 3.11)](../blob/master/chapters/projects/fetch.md)
* [x] [Testing](../blob/master/chapters/testing.md)
    * [x] [GoogleTest](../blob/master/chapters/testing/googletest.md)
    * [x] [Catch](../blob/master/chapters/testing/catch.md)
* [x] [Exporting and Installing](../blob/master/chapters/install.md)
    * [x] [Installing](../blob/master/chapters/install/installing.md)
    * [x] [Exporting](../blob/master/chapters/install/exporting.md)
    * [x] [Packaging](../blob/master/chapters/install/packaging.md)
* [x] [Looking for Libraries (Packages)](../blob/master/chapters/packages.md)
    * [x] [CUDA](../blob/master/chapters/packages/CUDA.md)
    * [x] [OpenMP](../blob/master/chapters/packages/OpenMP.md)
    * [x] [Boost](../blob/master/chapters/packages/Boost.md)
    * [x] [MPI](../blob/master/chapters/packages/MPI.md)
    * [x] [ROOT](../blob/master/chapters/packages/ROOT.md)
        * [x] [UseFile Example](../blob/master/examples/root-usefile/README.md)
        * [x] [Simple Example](../blob/master/examples/root-simple/README.md)
        * [x] [Dictionary Example](../blob/master/examples/root-dict/README.md)
    * [x] [Minuit2](../blob/master/chapters/packages/Minuit2.md)

**Comment by Smalldy** [comment]
请问此项目是否仍在维护

**Comment by zzsqwq** [comment]
> 请问此项目是否仍在维护

仍在维护，近期应该会继续推进。

**Comment by gilgamsh** [comment]
太强了 战神

**Comment by pi1ot** [comment]
麻烦请同步更新一下pdf版本，多谢

**Comment by zzsqwq** [comment]
> 麻烦请同步更新一下pdf版本，多谢

更新了[新的版本的 PDF](https://github.com/Modern-CMake-CN/Modern-CMake-zh_CN/blob/master/pdf/book.pdf)，但是由于 Gitbook 导出 PDF 的工具链多年失修等问题（甚至 Gitbook 也是闭源多年了），可能会有一些链接和样式存在问题。我也尝试了一些其他工具，效果也不太理想，只能暂时先这样了。

同时你也可以自己尝试使用 gitbook、gitbook-cli、NodeJS 14.12 导出。
