### ISSUE TITLE
CMake版本问题以及建议

### ISSUE THREAD

**Issue by Smalldy** [Modern-CMake-CN/Modern-CMake-zh_CN#22]
目前 cmake 已经由 kitware 支持维护 
apt官方源的版本过低且貌似不在跟进更新的版本（没有足够的资料支持 尚不确定），如果直接apt install 将会得到很低的版本，或许并不是很 modren 
```
sudo apt-get update
sudo apt-get install apt-transport-https ca-certificates gnupg software-properties-common wget
wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | sudo apt-key add -
sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
sudo apt-get update
sudo apt-get install cmake

```
以上方法可以增加 kitware 仓库，并更新最新的版本支持。

可考虑将此方案添加为新的章节或者作为附注插入文本中。

**Comment by ColourfulBlack** [comment]
Similar content can be found at this [paragraph](https://modern-cmake-cn.github.io/Modern-CMake-zh_CN/chapters/intro/installing.html#官方安装包). However, We really appreciate your advice.
I will close this issue, feel free to reopen it if you have any problem.
