### ISSUE TITLE
你好，可以提供pdf文件吗？

### ISSUE THREAD

**Issue by kisuke95** [Modern-CMake-CN/Modern-CMake-zh_CN#30]

**Comment by zzsqwq** [comment]
我目前导出了一个版本的 pdf，但是其中的某些排版可能并不优美，后续看看有没有改善的方法。

您也可以自己安装 gitbook-cli 来导出 pdf 文件。

链接：https://github.com/Modern-CMake-CN/Modern-CMake-zh_CN/blob/master/pdf/book.pdf
